plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/eyosiyasmekbib/Documents/Projects/ecran/.output/public"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm generate"
base = "/Users/eyosiyasmekbib/Documents/Projects/ecran/frontend"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]